characters:
    charlie: Charlie Barnes
    dakota: Dakota Travis
    evan: Evan Holwell
    jack: Jack Briarwood
    julia: Julia North

suspects:
    bria: Bria Brown
    cj: CJ Wallace
    david: David Nelson
    halvert: Mr Halvert
    ryan: Ryan Groggins

locations:
    barn: Barn
    lighthouse: Lighthouse
    nightclub: Nightclub
    park: State Park
    station: Train Station

searching:
    10k: 10000 Dollars
    alcohol: Bottle of Alcohol
    blade: Broken Switchblade
    blood: Drops of Blood
    firearm: Firearm
    followed: Followed
    mask: Mask
    van: White Van
