# List of characters
characters:
    # Call this <key>.
    # Can be anything, but it's best to make it the character's given name
    charlie:
        # The character's full name.
        full-name: Charlie Barnes
        # The name of the role to use when setting up the Discord server. Optional, defaults to <key>.capitalize()
        role: Charlie
        # How to display the character's name in the PDF export. Optional, defaults to replacing each space
        # in full-name with a line break.
        pdf-name-format:
            - Charlie
            - Barnes
    dakota:
        full-name: Dakota Travis
        # Note that this can be empty, or the "role" line can be removed entirely.
        role:
    evan:
        full-name: Evan Holwell
    jack:
        full-name: Jack Briarwood
    julia:
        full-name: Julia North

# List of suspects. Descriptions optional, colons are not.
suspects:
    bria: Bria Brown
    cj: CJ Wallace
    david: David Nelson
    halvert: Mr. Halvert
    ryan: Ryan Groggins

# List of locations. Descriptions optional, colons are not.
locations:
    barn: Barn
    lighthouse: Lighthouse
    nightclub: Nightclub
    park: State Park
    station: Train Station

# List of searching cards. Descriptions optional, colons are not.
searching:
    10k: 10000 Dollars
    alcohol: Bottle of Alcohol
    blade: Broken Switchblade
    blood: Drops of Blood
    firearm: Firearm
    followed: Followed
    mask: Mask
    van: White Van
