# All entries should be in the format <filename (no extension)>: <description>

characters:
    charlie:
        role: Charlie
        full-name: Charlie Barnes
        pdf-name-format:
            - Charlie
            - Barnes
    dakota:
        role:
        full-name: Dakota Travis
    evan:
        full-name: Evan Holwell
    jack:
        full-name: Jack Briarwood
    julia:
        full-name: Julia North

suspects:
    bria: Bria Brown
    cj: CJ Wallace
    david: David Nelson
    halvert: Mr. Halvert
    ryan: Ryan Groggins

locations:
    barn: Barn
    lighthouse: Lighthouse
    nightclub: Nightclub
    park: State Park
    station: Train Station

searching:
    10k: 10000 Dollars
    alcohol: Bottle of Alcohol
    blade: Broken Switchblade
    blood: Drops of Blood
    firearm: Firearm
    followed: Followed
    mask: Mask
    van: White Van
