name: Update Localization Tracker

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ vars.LOCALIZATION_TRACKER_ISSUE_NUMBER }}
        comment-author: 'github-actions[bot]'

    - name: Create comment
      if: steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ vars.LOCALIZATION_TRACKER_ISSUE_NUMBER }}
        body: |
          [github actions placeholder text]

    - name: Read CSV
      if: steps.fc.outputs.comment-id != ''
      id: csv
      uses: juliangruber/read-file-action@v1
      with:
        path: ./localization/localization-tracker.csv

    - name: Create MD
      if: steps.fc.outputs.comment-id != ''
      id: csv-to-md
      uses: petems/csv-to-md-table-action@master
      with:
        csvinput: ${{ steps.csv.outputs.content }}

    - name: Get timestamp
      id: timestamp
      if: steps.fc.outputs.comment-id != ''
      run: |
        echo "TIMESTAMP=$(git log -1 --date=iso-local --format="%ad" -- ./localization/localization-tracker.csv)" >> ${GITHUB_OUTPUT}

    - name: Render template
      id: template
      if: steps.fc.outputs.comment-id != ''
      uses: chuhlomin/render-template@v1.4
      with:
        template: .github/localization-tracker-header.md
        vars: |
          timestamp: ${{ steps.timestamp.outputs.TIMESTAMP }}

    - name: Insert header
      if: steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        edit-mode: replace
        body: ${{ steps.template.outputs.result }}

    - name: Update comment
      if: steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        edit-mode: append
        body: ${{ steps.csv-to-md.outputs.markdown-table }}
