# Attempt to log the bot in using a dummy Discord bot's token

name: Login Test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ vars.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test logging in
      env:
        WHITE_RABBIT_SHUTDOWN: true
        WHITE_RABBIT_TOKEN: ${{ secrets.WHITE_RABBIT_TOKEN }}
      run: |
        python ./src
